fix(SkinManageDialog): add missing QMenu include
launcher/ui/dialogs/skins/SkinManageDialog.cpp: In member function ‘void SkinManageDialog::show_context_menu(const QPoint&)’:
launcher/ui/dialogs/skins/SkinManageDialog.cpp:344:18: error: variable ‘QMenu myMenu’ has initializer but incomplete type
  344 |     QMenu myMenu(tr("Context menu"), this);
      |                  ^~

Include appears to have been dropped transitively in either
43f309e52241a0bac2031607fcd2095041da24b0 or 5c64f491355f303f979b3edb6931d93298d6a3d9

Signed-off-by: Alfred Wingate <parona@protonmail.com>